### ISSUE TITLE
Change MainViewController with MainTableViewController

### ISSUE THREAD

**Issue by mitsus** [dekatotoro/SlideMenuControllerSwift#11]
Hi dekatotoro,
congratulations for excellent work!
Just a question. I'm new in swift and in iOS programming ...so sorry for idiot question.
If i want change (into your sample app) MainViewController with a TableViewController?

I've tried to do this replacing MainViewController with MainTableViewController but i've an  correct error in appdelegate here: leftViewController.mainViewController = nvc

Please can you help me?

Thanks a lot and best Regards

**Comment by htarwara6245** [comment]
I did like this in my AppDelegate.I am using AuctionLatestViewController as MainViewController.It also include Table View,too.Hope this help
let mainViewController = storyboard.instantiateViewControllerWithIdentifier("AuctionLatestViewController") as AuctionLatestViewController
        
        let leftViewController = storyboard.instantiateViewControllerWithIdentifier("LeftMenuViewController") as LeftMenuViewController
        
        let nvc: UINavigationController = UINavigationController(rootViewController: mainViewController)

        // create viewController code...
        
        let slideMenuController = SlideMenuController(mainViewController:nvc, leftMenuViewController: leftViewController)

**Comment by mitsus** [comment]
Hi htarwara6245,
thank for you reply.

What about AuctionLatestViewController?

BR

**Comment by htarwara6245** [comment]
As you see,there are three controller in AppDelegate in my code.They are "mainViewController","leftViewController" and "slideMenuController"."nvc" is Navigation Controller for Navigation to several view.

AuctionLatestViewController is table view which is showing multiple of records.I set as initial view controller because i want it to appear that view when my app starts.That's why i add this in mainViewController.

LeftMenuController is my Slide Menu Table View which include multiple of menus to navigate to other view controller.

SlideMenuController is "dekatotoro" creation which has to be called at AppDelegate to embedded his slide to our app.

**Comment by mitsus** [comment]
Thanks a lot htarwara6245

**Comment by htarwara6245** [comment]
You r welcome,mitsus

**Comment by mrbamboovn** [comment]
Hello,

I am using this library and I have trouble when push new ViewController. Could you please suggest me how to push with UINavigationController ?

**Comment by dekatotoro** [comment]
Thank you htarwara6245 for the answer instead.
