### ISSUE TITLE
"track()" only called in left pan handler

### ISSUE THREAD

**Issue by ThomasPelster** [dekatotoro/SlideMenuControllerSwift#31]
e.g.

- func handleLeftPanGesture(panGesture: UIPanGestureRecognizer)
-- track(.FlickOpen)
-- track(.FlickClose)

- func handleRightPanGesture(panGesture: UIPanGestureRecognizer)
-- No tracking

**Comment by dekatotoro** [comment]
Oops, we will fix.

**Comment by tcalin** [comment]
It would be nice (useful?!) to have the `track` function also called here

`    func handleLeftPanGesture(panGesture: UIPanGestureRecognizer) {
        
        if !isTagetViewController() {
            return
        }
        
        if isRightOpen() {
            return
        }
        
        switch panGesture.state {
            case UIGestureRecognizerState.Began:
`

Maybe with a new TrackAction so that it can be ignored. I am trying to trigger something right after the drag begins and I don't want begin a fork just for this. Thank you!

**Comment by dekatotoro** [comment]
To close since the correspondence in this commit.
https://github.com/dekatotoro/SlideMenuControllerSwift/commit/020788d4089c604dfb3084c75f3ea2da142e0b04
